package by.javatr.financetracker.controller.command;

public enum CommandName {

    SIGN_UP, LOG_IN, EDIT_LOG_IN, CHANGE_PASSWORD, DEACTIVATE_USER_ACCOUNT,

    ADD_EXPENSE, EDIT_EXPENSE, DELETE_EXPENSE,
    ADD_INCOME, EDIT_INCOME, DELETE_INCOME,

    ADD_ACCOUNT, EDIT_ACCOUNT, DELETE_ACCOUNT,

    GET_TRANSACTIONS_HISTORY, GET_TRANSACTIONS_HISTORY_BY_DATE,
    GET_CURRENT_BALANCE, GET_ACCOUNTS, TRANSFER_MONEY,

    GET_EXPENSES_BY_CATEGORY, GET_INCOMES_BY_CATEGORY,
    WRONG_REQUEST,
}
